Console.Write("Введите b1: ");
double b1 = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите k1: ");
double k1 = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите b2: ");
double b2 = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите k2: ");
double k2 = Convert.ToDouble(Console.ReadLine());
double x = Math.Round((b2 - b1)/(k1 - k2), 2);
double y = Math.Round(k1*x + b1, 2);
 Console.WriteLine($"Точка пересечения: ({x};{y}) ");
